[project]
name = "TopDownBundle"
version = "1.0.0"
created = "2025-08-28T20:32:34.920817717Z"
modified = "2026-03-19T22:18:42.407585172Z"
toki_editor_version = "0.1.0"
description = ""

[scenes]
"Scene 2" = "scenes/Scene 2.json"
main = "scenes/main.json"
"Main Scene" = "scenes/Main Scene.json"

[assets]
sprites = "assets/sprites/"
tilemaps = "assets/tilemaps/"
audio = "assets/audio/"

[runtime.splash]
duration_ms = 1200

[runtime.audio]
master_percent = 100
music_percent = 80
movement_percent = 80
collision_percent = 10

[runtime.display]
show_entity_health_bars = true
resolution_width = 160
resolution_height = 144
zoom_percent = 100
vsync = false
target_fps = 30
timing_mode = "delta"

[runtime.menu]
pause_root_screen_id = "pause_menu"
gate_gameplay_when_open = true

[runtime.menu.appearance]
font_family = "Serif"
font_size_px = 30
menu_width_percent = 65
menu_height_percent = 85
title_spacing_px = 32
button_spacing_px = 12
footer_spacing_px = 128
opacity_percent = 50
border_color_hex = "#7CFF7C"
text_color_hex = "#FFFFFF"
menu_background_color_hex = "#142914"
menu_background_transparent = false
title_background_color_hex = "#143614"
title_background_transparent = true
entry_background_color_hex = "#0F1F0F"
entry_background_transparent = false
footer_text = """
          Esc: Back   
Enter/Space: Select"""
border_style = "square"

[[runtime.menu.screens]]
id = "pause_menu"
title = "Paused"
title_border_style_override = "none"

[[runtime.menu.screens.items]]
kind = "button"
text = "Resume"

[runtime.menu.screens.items.action]
kind = "close_ui"

[[runtime.menu.screens.items]]
kind = "button"
text = "Inventory"

[runtime.menu.screens.items.action]
kind = "open_surface"
surface_id = "inventory_menu"

[[runtime.menu.screens.items]]
kind = "button"
text = "Exit Game"

[runtime.menu.screens.items.action]
kind = "open_surface"
surface_id = "end_game"

[[runtime.menu.screens]]
id = "inventory_menu"
title = "Inventory"

[[runtime.menu.screens.items]]
kind = "dynamic_list"
heading = "Items"
source = "player_inventory"
empty_text = "Inventory is empty"

[[runtime.menu.screens.items]]
kind = "button"
text = "Back"

[runtime.menu.screens.items.action]
kind = "back"

[[runtime.menu.dialogs]]
id = "end_game"
title = "End Game"
body = "Are you sure?"
confirm_text = "Confirm"
cancel_text = "Cancel"
hide_main_menu = true

[runtime.menu.dialogs.confirm_action]
kind = "exit_runtime"

[runtime.menu.dialogs.cancel_action]
kind = "close_surface"

[editor]
recent_files = []

[editor.camera_settings]

[editor.graph_layouts."Scene 2"]
zoom = 0.8264462351799011
pan = [
    -74.87890625,
    64.38671875,
]

[editor.graph_layouts."Scene 2".node_positions]
"node:2" = [
    800.0,
    50.0,
]
"node:1" = [
    60.0,
    50.0,
]
"node:4" = [
    656.8824462890625,
    177.01071166992188,
]
"node:3" = [
    430.0,
    50.0,
]

[editor.graph_layouts."Main Scene"]
zoom = 0.791378378868103
pan = [
    35.512847900390625,
    -24.64453125,
]

[editor.graph_layouts."Main Scene".node_positions]
"node:9" = [
    430.0,
    162.0,
]
"node:2" = [
    800.0,
    50.0,
]
"node:5" = [
    800.0,
    106.0,
]
"node:3" = [
    430.0,
    50.0,
]
"node:10" = [
    60.0,
    218.0,
]
"node:1" = [
    60.0,
    50.0,
]
"node:15" = [
    430.0,
    274.0,
]
"node:13" = [
    60.0,
    274.0,
]
"node:12" = [
    430.0,
    218.0,
]
"node:11" = [
    800.0,
    218.0,
]
"node:8" = [
    800.0,
    162.0,
]
"node:7" = [
    60.0,
    162.0,
]
"node:6" = [
    430.0,
    106.0,
]
"node:4" = [
    60.0,
    106.0,
]
"node:14" = [
    800.0,
    274.0,
]

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 1
position = [
    60.0,
    50.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Trigger.OnCollision]

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 2
position = [
    800.0,
    50.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Action.PlaySound]
channel = "Collision"
sound_id = "sfx_hit"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 3
position = [
    430.0,
    50.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind]
Condition = "Always"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 4
position = [
    60.0,
    106.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Trigger.OnInteract]
mode = "InFront"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 5
position = [
    800.0,
    106.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Action.PlaySound]
channel = "Movement"
sound_id = "sfx_powerup"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 6
position = [
    430.0,
    106.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind]
Condition = "Always"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 7
position = [
    60.0,
    162.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Trigger.OnDamaged.entity]
Entity = 9

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 8
position = [
    800.0,
    162.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Action.SwitchScene]
scene_name = "Scene 2"
spawn_point_id = "spawn_point_1"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 9
position = [
    430.0,
    162.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Condition.HealthBelow]
threshold = 50

[editor.rule_graph_drafts."Main Scene".nodes.kind.Condition.HealthBelow.target]
Entity = 9

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 10
position = [
    60.0,
    218.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Trigger.OnDeath]

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 11
position = [
    800.0,
    218.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Action.PlaySound]
channel = "Movement"
sound_id = "sfx_select"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 12
position = [
    430.0,
    218.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Condition.EntityIsKind]
target = "TriggerSelf"
kind = "Npc"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 13
position = [
    60.0,
    274.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Trigger.OnTileEnter]
x = 1
y = 23

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 14
position = [
    800.0,
    274.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Action.SwitchScene]
scene_name = "Main Scene"
spawn_point_id = "spawn_point_2"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 15
position = [
    430.0,
    274.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind]
Condition = "Always"

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 3
to = 2

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 1
to = 3

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 6
to = 5

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 4
to = 6

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 9
to = 8

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 7
to = 9

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 12
to = 11

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 10
to = 12

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 15
to = 14

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 13
to = 15

[[editor.rule_graph_drafts."Main Scene".chains]]
rule_id = "rule_2"
enabled = true
priority = 0
once = false
trigger_node_id = 1

[[editor.rule_graph_drafts."Main Scene".chains]]
rule_id = "rule_1"
enabled = true
priority = 0
once = false
trigger_node_id = 4

[[editor.rule_graph_drafts."Main Scene".chains]]
rule_id = "rule_3"
enabled = true
priority = 0
once = false
trigger_node_id = 7

[[editor.rule_graph_drafts."Main Scene".chains]]
rule_id = "rule_4"
enabled = true
priority = 0
once = false
trigger_node_id = 10

[[editor.rule_graph_drafts."Main Scene".chains]]
rule_id = "rule_5"
enabled = true
priority = 0
once = false
trigger_node_id = 13
