[project]
name = "NewProject"
version = "1.0.0"
created = "2025-08-28T20:32:34.920817717Z"
modified = "2026-03-15T11:37:24.369211675Z"
toki_editor_version = "0.1.0"
description = ""

[scenes]
"Main Scene" = "scenes/mainscene.json"
main = "scenes/main.json"
"Scene 2" = "scenes/scene2.json"

[assets]
sprites = "assets/sprites/"
tilemaps = "assets/tilemaps/"
audio = "assets/audio/"

[runtime.splash]
duration_ms = 1200

[runtime.audio]
master_percent = 100
music_percent = 80
movement_percent = 80
collision_percent = 10

[editor]
recent_files = []

[editor.camera_settings]

[editor.graph_layouts."Main Scene"]
zoom = 0.791378378868103
pan = [
    89.1378402709961,
    16.0,
]

[editor.graph_layouts."Main Scene".node_positions]
"node:2" = [
    800.0,
    50.0,
]
"node:4" = [
    60.0,
    106.0,
]
"node:1" = [
    60.0,
    50.0,
]
"node:3" = [
    430.0,
    50.0,
]
"node:6" = [
    430.0,
    106.0,
]
"node:5" = [
    800.0,
    106.0,
]

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 1
position = [
    60.0,
    50.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind]
Trigger = "OnStart"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 2
position = [
    800.0,
    50.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Action.PlayMusic]
track_id = "lavandia"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 3
position = [
    430.0,
    50.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind]
Condition = "Always"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 4
position = [
    60.0,
    106.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind]
Trigger = "OnCollision"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 5
position = [
    800.0,
    106.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind.Action.PlaySound]
channel = "Collision"
sound_id = "sfx_hit"

[[editor.rule_graph_drafts."Main Scene".nodes]]
id = 6
position = [
    430.0,
    106.0,
]

[editor.rule_graph_drafts."Main Scene".nodes.kind]
Condition = "Always"

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 3
to = 2

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 1
to = 3

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 6
to = 5

[[editor.rule_graph_drafts."Main Scene".edges]]
from = 4
to = 6

[[editor.rule_graph_drafts."Main Scene".chains]]
rule_id = "rule_1"
enabled = true
priority = 0
once = false
trigger_node_id = 1

[[editor.rule_graph_drafts."Main Scene".chains]]
rule_id = "rule_2"
enabled = true
priority = 0
once = false
trigger_node_id = 4
