[project]
name = "TopDownBundle"
version = "1.0.0"
created = "2025-08-28T20:32:34.920817717Z"
modified = "2026-03-29T13:56:48.600743843Z"
toki_editor_version = "0.1.0"
description = ""

[scenes]
"Scene 2" = "scenes/Scene 2.json"
main = "scenes/main.json"
"Main Scene" = "scenes/Main Scene.json"

[assets]
sprites = "assets/sprites/"
tilemaps = "assets/tilemaps/"
audio = "assets/audio/"

[runtime]
scene_persistence = true

[runtime.splash]
duration_ms = 1200

[runtime.audio]
master_percent = 100
music_percent = 80
movement_percent = 80
collision_percent = 10

[runtime.display]
show_entity_health_bars = true
show_ground_shadows = true
resolution_width = 160
resolution_height = 144
zoom_percent = 100
vsync = false
target_fps = 30
timing_mode = "delta"

[runtime.display.post_process]
mode = "none"
quantize_strategy = "luminance"
tint_color = [
    32,
    64,
    96,
    255,
]
tint_strength_percent = 35
brightness_percent = 0
saturation_percent = 100
quantize_palette_id = "gray"
gb_contrast_percent = 0
vignette_strength_percent = 60

[runtime.display.viewport]
mode = "integer_scale"
factor = "auto"

[runtime.menu]
pause_root_screen_id = "pause_menu"
gate_gameplay_when_open = true

[runtime.menu.appearance]
font_family = "Serif"
font_size_px = 30
menu_width_percent = 65
menu_height_percent = 85
title_spacing_px = 32
button_spacing_px = 12
footer_spacing_px = 128
opacity_percent = 50
border_thickness_px = 2
border_color_hex = "#7CFF7C"
text_color_hex = "#FFFFFF"
menu_background_color_hex = "#142914"
menu_background_transparent = false
title_background_color_hex = "#143614"
title_background_transparent = true
entry_background_color_hex = "#0F1F0F"
entry_background_transparent = false
footer_text = """
          Esc: Back   
Enter/Space: Select"""
border_style = "square"
dialog_position = "top"

[runtime.menu.appearance.dialog_speaker_text]
font_family = "Sans"
font_size_px = 18
bold = true
cursive = false

[runtime.menu.appearance.dialog_body_text]
font_family = "Sans"
font_size_px = 14
bold = false
cursive = false

[[runtime.menu.screens]]
id = "pause_menu"
title = "Paused"
title_border_style_override = "none"

[[runtime.menu.screens.items]]
kind = "button"
text = "Resume"

[runtime.menu.screens.items.action]
kind = "close_ui"

[[runtime.menu.screens.items]]
kind = "button"
text = "Inventory"

[runtime.menu.screens.items.action]
kind = "open_surface"
surface_id = "inventory_menu"

[[runtime.menu.screens.items]]
kind = "button"
text = "Audio Settings"

[runtime.menu.screens.items.action]
kind = "open_audio_settings"

[[runtime.menu.screens.items]]
kind = "button"
text = "Graphics Settings"

[runtime.menu.screens.items.action]
kind = "open_graphics_settings"

[[runtime.menu.screens.items]]
kind = "button"
text = "Display Settings"

[runtime.menu.screens.items.action]
kind = "open_display_settings"

[[runtime.menu.screens.items]]
kind = "button"
text = "Save Game"

[runtime.menu.screens.items.action]
kind = "save_game"
slot = 1

[[runtime.menu.screens.items]]
kind = "button"
text = "Load Game"

[runtime.menu.screens.items.action]
kind = "load_game"
slot = 1

[[runtime.menu.screens.items]]
kind = "button"
text = "Exit Game"

[runtime.menu.screens.items.action]
kind = "open_surface"
surface_id = "end_game"

[[runtime.menu.screens]]
id = "inventory_menu"
title = "Inventory"

[[runtime.menu.screens.items]]
kind = "dynamic_list"
heading = "Items"
source = "player_inventory"
empty_text = "Inventory is empty"

[[runtime.menu.screens.items]]
kind = "button"
text = "Back"

[runtime.menu.screens.items.action]
kind = "back"

[[runtime.menu.dialogs]]
id = "end_game"
title = "End Game"
body = "Are you sure?"
confirm_text = "Confirm"
cancel_text = "Cancel"
hide_main_menu = true

[runtime.menu.dialogs.confirm_action]
kind = "exit_runtime"

[runtime.menu.dialogs.cancel_action]
kind = "close_surface"

[[runtime.menu.dialogs]]
id = "new_dialog"
title = "New Dialog"
body = "Are you sure?"
confirm_text = "Confirm"
cancel_text = "Cancel"

[runtime.menu.dialogs.confirm_action]
kind = "close_surface"

[runtime.menu.dialogs.cancel_action]
kind = "close_surface"

[runtime.dialog_appearance]
font_family = "Mono"
font_size_px = 14
menu_width_percent = 60
menu_height_percent = 60
title_spacing_px = 6
button_spacing_px = 6
footer_spacing_px = 6
opacity_percent = 70
border_thickness_px = 4
border_color_hex = "#000000"
text_color_hex = "#000000"
menu_background_color_hex = "#FFFFFF"
menu_background_transparent = false
title_background_color_hex = "#FFFFFF"
title_background_transparent = false
entry_background_color_hex = "#FFFFFF"
entry_background_transparent = false
footer_text = "Esc: Back   Enter/Space: Select"
border_style = "square"
dialog_position = "bottom"

[runtime.dialog_appearance.dialog_speaker_text]
font_family = "Sans"
font_size_px = 18
bold = false
cursive = false

[runtime.dialog_appearance.dialog_body_text]
font_family = "Sans"
font_size_px = 16
bold = false
cursive = true

[runtime.ui]
event_declarations = []

[runtime.ui.theme]
font_family = "Sans"
base_font_size_px = 14
foreground_color = [
    240,
    240,
    240,
    255,
]
background_color = [
    12,
    18,
    28,
    224,
]
accent_color = [
    100,
    220,
    180,
    255,
]
border_color = [
    255,
    255,
    255,
    255,
]
border_thickness_px = 1
progress_fill_color = [
    80,
    220,
    120,
    255,
]
progress_empty_color = [
    32,
    48,
    56,
    255,
]
selection_color = [
    255,
    210,
    90,
    255,
]

[runtime.ui.theme.default_spacing]
left = 4
top = 4
right = 4
bottom = 4

[[runtime.flags.declarations]]
id = "coins"

[runtime.flags.declarations.default_value]
type = "int"
value = 0

[[runtime.flags.declarations]]
id = "has_coins"

[runtime.flags.declarations.default_value]
type = "bool"
value = true

[runtime.scene_transitions]
default_effect = "fade"
default_duration_ms = 250

[editor]
recent_files = []

[editor.camera_settings]

[editor.graph_layouts."Scene 2"]
zoom = 0.8264462351799011
pan = [
    -74.87890625,
    64.38671875,
]

[editor.graph_layouts."Scene 2".node_positions]
"node:2" = [
    800.0,
    50.0,
]
"node:1" = [
    60.0,
    50.0,
]
"node:3" = [
    430.0,
    50.0,
]
"node:4" = [
    656.8824462890625,
    177.01071166992188,
]

[editor.graph_layouts."Main Scene"]
zoom = 0.8088202476501465
pan = [
    50.0,
    16.0,
]

[editor.graph_layouts."Main Scene".node_positions]
"node:6" = [
    488.640625,
    112.984375,
]
"node:18" = [
    483.578125,
    307.609375,
]
"node:9" = [
    615.984375,
    161.640625,
]
"node:14" = [
    60.0,
    258.953125,
]
"node:20" = [
    60.0,
    356.265625,
]
"node:10" = [
    318.65625,
    161.640625,
]
"node:16" = [
    262.625,
    258.953125,
]
"node:13" = [
    293.71875,
    210.296875,
]
"node:19" = [
    259.625,
    307.609375,
]
"node:22" = [
    240.34375,
    356.265625,
]
"node:7" = [
    244.359375,
    112.984375,
]
"node:3" = [
    246.0,
    64.328125,
]
"node:11" = [
    60.0,
    210.296875,
]
"node:2" = [
    469.625,
    64.328125,
]
"node:8" = [
    60.0,
    161.640625,
]
"node:5" = [
    758.296875,
    64.328125,
]
"node:21" = [
    452.296875,
    356.265625,
]
"node:12" = [
    584.375,
    210.296875,
]
"node:15" = [
    522.25,
    258.953125,
]
"node:17" = [
    60.0,
    307.609375,
]
"node:4" = [
    60.0,
    112.984375,
]
"node:1" = [
    60.0,
    64.328125,
]

[editor.rule_graph_drafts]

[editor.dialog_graph_layouts.dialog_1]
zoom = 0.683013379573822
pan = [
    60.984375,
    6.97265625,
]

[editor.dialog_graph_layouts.dialog_1.node_positions]
end = [
    720.0,
    80.0,
]
line = [
    400.0,
    80.0,
]
start = [
    80.0,
    80.0,
]

[editor.ui_layout_views.ui_1]
zoom = 2.68601393699646
pan = [
    123.58984375,
    34.6328125,
]
selected_widget_id = "label_1"

[editor.ui_layout_views.ui_2]
zoom = 1.0
pan = [
    12.0,
    12.0,
]
selected_widget_id = "label_1"
